server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;
    gzip on;
    gzip_types text/css application/javascript image/svg+xml;
    gzip_min_length 512;
    location / { try_files $uri $uri/ $uri.html =404; add_header Cache-Control "public, max-age=600"; }
    location ~* \.(webp|woff2|mp4|css)$ { add_header Cache-Control "public, max-age=2592000"; }
}
